import { IrregularVerb, IrregularVerbs } from '../assets/types/verbs';

const verb = (i: string, ps: string, pp: string, t: string): IrregularVerb => {
  return {
    key: i,
    infinitive: i,
    pastSimple: ps,
    pastParticipant: pp,
    translation: t,
  };
};

export const irregularVerbs: IrregularVerbs = [
  // A
  verb('arise', 'arose', 'arisen', 'возникать, появляться'),
  verb('awake', 'awoke', 'awoken', 'будить, просыпаться'),
  // B
  verb('backslide', 'backslid', 'backslid', 'отступаться от веры'),
  verb('be', 'was/were', 'been', 'быть'),
  verb('bear', 'bore', 'born', 'рождать, приносить'),
  verb('beat', 'beat', 'beaten', 'бить'),
  verb('become', 'became', 'become', 'становиться'),
  verb('befall', 'befell', 'befallen', 'приключаться, происходить'),
  verb('begin', 'began', 'begun', 'начинать'),
  verb('bend', 'bent', 'bent', 'гнуть, сгибать'),
  verb('bind', 'bound', 'bound', 'связывать'),
  verb('bite', 'bit', 'bitten', 'кусать'),
  verb('bleed', 'bled', 'bled', 'кровоточить'),
  verb('blow', 'blew', 'blown', 'дуть'),
  verb('break', 'broke', 'broken', 'ломать(ся), прекращать'),
  verb('breed', 'bred', 'bred', 'воспитывать'),
  verb('bring', 'brought', 'brought', 'приносить'),
  verb('browbeat', 'browbeat', 'browbeaten', 'запугивать, наводить страх'),
  verb('build', 'built', 'built', 'строить'),
  verb('burn', 'burnt', 'burnt', 'гореть, жечь'),
  verb('burst', 'burst', 'burst', 'разразиться, взрывать(ся)'),
  verb('buy', 'bought', 'bought', 'покупать'),
  // C
  verb('cast', 'cast', 'cast', 'кинуть, лить (металл)'),
  verb('catch', 'caught', 'caught', 'ловить, схватывать'),
  verb('choose', 'chose', 'chosen', 'выбирать, подбирать'),
  verb('come', 'came', 'come', 'приходить'),
  verb('cost', 'cost', 'cost', 'стоить'),
  verb('cut', 'cut', 'cut', 'резать'),
  // D
  verb('dig', 'dug', 'dug', 'рыть, копать'),
  verb('do', 'did', 'done', 'делать'),
  verb('draw', 'drew', 'drawn', 'рисовать, тащить'),
  verb('dream', 'dreamt', 'dreamt', 'мечтать, сниться'),
  verb('drink', 'drank', 'drunk', 'пить'),
  verb('drive', 'drove', 'driven', 'водить, управлять (машиной)'),
  // E
  verb('eat', 'ate', 'eaten', 'есть'),
  // F
  verb('fall', 'fell', 'fallen', 'падать'),
  verb('feed', 'fed', 'fed', 'кормить'),
  verb('feel', 'felt', 'felt', 'чувствовать'),
  verb('fight', 'fought', 'fought', 'бороться'),
  verb('find', 'found', 'found', 'находить'),
  verb('fit', 'fit', 'fit', 'соответствовать, подходить'),
  verb('fly', 'flew', 'flown', 'летать'),
  verb('forbear', 'forbore', 'forborne', 'сдерживаться'),
  verb('forbid', 'forbad', 'forbidden', 'запрещать, не позволять'),
  verb('foresee', 'foresaw', 'foreseen', 'предвидеть'),
  verb('forget', 'forgot', 'forgotten', 'забывать'),
  verb('forgive', 'forgave', 'forgiven', 'прощать'),
  verb('freeze', 'froze', 'frozen', 'замерзать'),
  // G
  verb('get', 'got', 'got', 'получать'),
  verb('give', 'gave', 'given', 'давать'),
  verb('go', 'went', 'gone', 'идти, ходить'),
  verb('grind', 'ground', 'ground', 'молоть'),
  verb('grow', 'grew', 'grown', 'расти'),
  // H
  verb('hang', 'hung', 'hung', 'висеть, развешивать'),
  verb('have', 'had', 'had', 'иметь'),
  verb('hear', 'heard', 'heard', 'слышать'),
  verb('hide', 'hid', 'hidden', 'прятать'),
  verb('hit', 'hit', 'hit', 'ударять, попадать в цель'),
  verb('hold', 'held', 'held', 'держать'),
  verb('hurt', 'hurt', 'hurt', 'ранить, причинить боль'),
  // I
  verb('interweave', 'interwove', 'interwoven', 'сплетать, прошивать'),
  // K
  verb('keep', 'kept', 'kept', 'держать, сохранять'),
  verb('kneel', 'knelt', 'knelt', 'становиться на колени'),
  verb('knit', 'knit', 'knit', 'вязать (спицами)'),
  verb('know', 'knew', 'known', 'знать'),
  // L
  verb('lay', 'laid', 'laid', 'класть, положить'),
  verb('lead', 'led', 'led', 'вести, возглавлять'),
  verb('lean', 'leant', 'leant', 'наклоняться'),
  verb('learn', 'learnt', 'learnt', 'учить'),
  verb('leave', 'left', 'left', 'оставлять, покидать'),
  verb('lend', 'lent', 'lent', 'занимать, одалживать'),
  verb('let', 'let', 'let', 'позволять'),
  verb('lie', 'lay', 'lain', 'лежать'),
  verb('light', 'lit', 'lit', 'освещать, зажигать'),
  verb('lose', 'lost', 'lost', 'терять'),
  // M
  verb('make', 'made', 'made', 'делать (производить)'),
  verb('mean', 'meant', 'meant', 'значить'),
  verb('meet', 'met', 'met', 'встречать'),
  verb('mislead', 'misled', 'misled', 'вводить в заблуждение'),
  verb('mistake', 'mistook', 'mistaken', 'ошибаться'),
  verb('mow', 'mowed', 'mown', 'косить, жать'),
  // O
  verb('overcome', 'overcame', 'overcome', 'преодолевать'),
  verb('overtake', 'overtook', 'overtaken', 'обгонять'),
  // P
  verb('partake', 'partook', 'partaken', 'принимать участие'),
  verb('pay', 'paid', 'paid', 'платить'),
  verb('put', 'put', 'put', 'класть, ставить'),
  // R
  verb('read', 'read', 'read', 'читать'),
  verb('ride', 'rode', 'ridden', 'ехать верхом'),
  verb('ring', 'rang', 'rung', 'звонить, звенеть'),
  verb('rise', 'rose', 'risen', 'подниматься'),
  verb('rive', 'rived', 'riven', 'разрывать, раскалывать'),
  verb('run', 'ran', 'run', 'бежать'),
  // S
  verb('say', 'said', 'said', 'говорить'),
  verb('see', 'saw', 'seen', 'видеть'),
  verb('seek', 'sought', 'sought', 'искать'),
  verb('sell', 'sold', 'sold', 'продавать'),
  verb('send', 'sent', 'sent', 'посылать'),
  verb('set', 'set', 'set', 'ставить, устанавливать'),
  verb('shake', 'shook', 'shaken', 'трясти'),
  verb('shear', 'sheared', 'shorn', 'стричь, резать'),
  verb('shine', 'shone', 'shone', 'светить, сиять, блестеть'),
  verb('shoot', 'shot', 'shot', 'стрелять'),
  verb('show', 'showed', 'shown', 'показывать'),
  verb('shrink', 'shrank', 'shrunk', 'уменьшать(ся), сокращать(ся)'),
  verb('shut', 'shut', 'shut', 'закрывать'),
  verb('sing', 'sang', 'sung', 'петь'),
  verb('sink', 'sank', 'sunk', 'тонуть'),
  verb('sit', 'sat', 'sat', 'сидеть'),
  verb('sleep', 'slept', 'slept', 'спать'),
  verb('slide', 'slid', 'slid', 'скользить'),
  verb('smell', 'smelt', 'smelt', 'нюхать, пахнуть'),
  verb('sow', 'sowed', 'sown', 'сеять, засевать'),
  verb('speak', 'spoke', 'spoken', 'говорить, разговаривать'),
  verb('spell', 'spelt', 'spelt', 'произносить'),
  verb('spend', 'spent', 'spent', 'тратить'),
  verb('spill', 'spilt', 'spilt', 'проливать'),
  verb('spit', 'spat', 'spat', 'плевать'),
  verb('split', 'split', 'split', 'расщеплять, разделять'),
  verb('spoil', 'spoilt', 'spoilt', 'портить'),
  verb('spotlight', 'spotlit', 'spotlit', 'осветить'),
  verb('spread', 'spread', 'spread', 'распространять(ся)'),
  verb('stand', 'stood', 'stood', 'стоять'),
  verb('steal', 'stole', 'stolen', 'воровать, красть'),
  verb('stick', 'stuck', 'stuck', 'приклеивать(ся)'),
  verb('sting', 'stung', 'stung', 'жалить'),
  verb('strike', 'struck', 'struck', 'ударять, бастовать'),
  verb('strive', 'strove', 'striven', 'стараться, стремиться'),
  verb('swear', 'swore', 'sworn', 'давать клятву'),
  verb('sweep', 'swept', 'swept', 'мести, подметать'),
  verb('swim', 'swam', 'swum', 'плавать'),
  // T
  verb('take', 'took', 'taken', 'брать, взять'),
  verb('teach', 'taught', 'taught', 'учить, обучать'),
  verb('tear', 'tore', 'torn', 'рвать'),
  verb('tell', 'told', 'told', 'рассказывать'),
  verb('think', 'thought', 'thought', 'думать'),
  verb('throw', 'threw', 'thrown', 'бросать'),
  verb('tread', 'trod', 'trod', 'идти, шагать'),
  // U
  verb('understand', 'understood', 'understood', 'понимать'),
  verb('uphold', 'upheld', 'upheld', 'поддерживать'),
  verb('upset', 'upset', 'upset', 'огорчать, расстраивать (планы)'),
  // W
  verb('wake', 'woke', 'woken', 'просыпаться'),
  verb('wear', 'wore', 'worn', 'носить'),
  verb('weep', 'wept', 'wept', 'плакать'),
  verb('wet', 'wet', 'wet', 'мочить, увлажнять'),
  verb('win', 'won', 'won', 'выигрывать, побеждать'),
  verb('wind', 'wound', 'wound', 'извиваться, обматывать'),
  verb('withdraw', 'withdrew', 'withdrawn', 'забирать'),
  verb('wring', 'wrung', 'wrung', 'крутить, выламывать'),
  verb('write', 'wrote', 'written', 'писать'),
];
