# This is a basic workflow to help you get started with Actions

name: PR-to-Main

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run ESLint
        run: npm run lint
